"""Initial

Revision ID: ab7203557ded
Revises: 
Create Date: 2020-12-21 17:43:36.724219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab7203557ded'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('repositories',
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('name', sa.String(length=200), autoincrement=False, nullable=False),
    sa.Column('private', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(length=80), nullable=False),
    sa.Column('updated_at', sa.String(length=80), nullable=False),
    sa.Column('size', sa.String(length=100), nullable=False),
    sa.Column('stargazers_count', sa.String(length=100), nullable=False),
    sa.Column('watchers_count', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repositories')
    op.drop_table('users')
    # ### end Alembic commands ###
